### ISSUE TITLE
Missing videos from playlists (youtube bug?)

### ISSUE THREAD

**Issue by Keith94** [shgysk8zer0/youtube-subscribe-addon#3]
### Steps to reproduce
1.  Go to https://www.youtube.com/playlist?list=PLw4Vbi28NT4_UghDQpQ63R9VbR8WhzfGS
2.  Click the YouTube Feeds icon

### Expected behavior
All seven videos should be displayed

### Actual behavior
Only displays five videos

### Screenshots
![image](https://user-images.githubusercontent.com/5490615/32818660-6aef2a0e-c979-11e7-94f6-2b3e4bfa83b0.png)

**Comment by shgysk8zer0** [comment]
I thought I responded to this a long time ago.

Yeah, this would be on YouTube's end. This add-on only pulls out the URL for the feed. Has nothing to do with generating or parsing. However, some feed readers will keep old content even after the items have been removed from the feed, in which case you would still be able to access those videos pretty easily, provided you used such a reader and had been subscribed long enough.
